pub mod closure;
pub mod combinator;
pub mod control_flow;
pub mod collection;
// pub mod structure;
pub mod derive;
pub mod ext_crate;
pub mod hashmap;
pub mod input;
pub mod iterator;
pub mod int_module;
pub mod option_type;
pub mod ownership;
pub mod repetition;
// pub mod result_type;
pub mod some;